name: Boot Manifest Verify

on:
  push:
    paths:
      - 'boot/**'
  pull_request:
    paths:
      - 'boot/**'

jobs:
  verify-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Run manifest verifier
        run: |
          python scripts/ci/verify_boot_manifest.py
